server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your-database
    username: 'your-user'
    password: 'your-password'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import:
      - classpath:config.yml
      - classpath:localization.yml
      - optional:classpath:git.properties