telegram:
  channel-check-subscribe: '@leykastars'
  channel-check-subscribe-url: 'https://t.me/leykastars'
  log-channel-id: -1003793323415
  log-channel-topic-id: 2
  bot:
    token: '8536529679:AAHMbLRNmjiaFYMo9DL7QITvKdGUnvJq0y4'
    name: 'leykadev_bot'

dev-mode:
  enable: true
  whitelist:
    - 6533681747

stars:
  markup: 1.3

premium:
  markup: 1.3

ton:
  network:
    type: mainnet
    timeout: 30000 # в течение скольки времени (в миллесекундах) будет проходить проверка соединения
    checkout: 2000 # каждые сколько миллисекунд будет проверка соединения
  wallet:
    mnemonic: "company promote injury bless parent frown tiny sport dynamic globe marine engage pizza various project lake image primary artwork into diet base yellow all"
    api-key: "0b7a752f555fc7d79977b7578a0385d6ee0f2aadd568554135cb6a076f5100e4"
    address: 'UQC3iHb-RVzoykSwEEx0d2IbC8FFsiNElIhF2nqn5J0K1bxf'

platega:
  api: 'AeMGYmle1lOjE4smVdmJw0B6zjul3euJalXc4aPFoHxCsNETq74CS9pA2gCxPf6qe2fekDohJvE9mQl0e0luBbNemECG0AQIYkfY'
  merchant-id: 'c3b306ac-18cf-45fb-a3aa-af9849c8d677'
  makeup:
    sbpqr: 1.4
    card: 1.5
    crypto: 1.1

fragment:
  api-url: https://fragment.com/api
  hash: 5e8d967d101586dec1
  cookies: stel_ssid=9af73ac18a72a02ef5_11297726451979062422; stel_dt=-180; stel_token=772998c109c450fc1eb86074db6d2fcc772998db772990b5a779b38656e188546550b; stel_ton_token=QOxxqjpVvAQkPjA4Xwdv7N1RqpQ6Zd5fGIwJEfUOdH-4KY007mgAHkCq8NrAQFabg8JpRSQvB3g9IzWXq3HBESOwGXqVluiby2k3m0fMeWF-b-REtvBegl0nXY_w3GXKVyFPWBkhTlM90X0BStmvNWJFO_yrphL2QaVlQxiX0VH90pYNJx1ZZC2i4XCA3oSNNG113xxt