name: 'deploy for main branch'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'ssh and deploy'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/tg/LeykaShopBot
            git pull origin main
            
            # Записываем инфо о коммите в файл
            echo "app.commit.hash=$(git rev-parse --short HEAD)" > src/main/resources/git.properties
            echo "app.commit.message=$(git log -1 --pretty=%s)" >> src/main/resources/git.properties
            echo "app.commit.author=$(git log -1 --pretty=%an)" >> src/main/resources/git.properties
            
            docker-compose stop leykabot
            docker-compose rm -f leykabot
            docker-compose up -d --build leykabot